### ISSUE TITLE
invalid pom file: Unrecognised tag: 'build'

### ISSUE THREAD

**Issue by ericdallo** [jlesquembre/clojars-publish-action#2]
https://github.com/clojure-lsp/clojure-lsp/pull/465/checks?check_run_id=2991331770

Hi, when deploying to clojars it complains about the `build` tag, but that seems correct as depstar also fills that when syncing the pom.
If I remove it it works, but every pom sync from depstar it adds again

**Comment by jlesquembre** [comment]
I think it could be related to https://clojure.atlassian.net/browse/TDEPS-152
I suspect that the action is using an old clojure version, I'm investigating it

**Comment by ericdallo** [comment]
Yeah, I found that issue, but it looked a different issue to me, anyway, thanks for investigate it

**Comment by jlesquembre** [comment]
I was able to reproduce the error: https://github.com/jlesquembre/dummy-clj/runs/2997491894?check_suite_focus=true
It was TDEPS-152, if you update to the 0.4 version, it should work

**Comment by ericdallo** [comment]
Thank you! I'll give a try next release

**Comment by jlesquembre** [comment]
Nice, looks like it works: https://github.com/clojure-lsp/clojure-lsp/runs/3046690124?check_suite_focus=true

Nice to see you using this action, I'm a happy clojure-lsp user :) 

If you find any other issues, ping me

**Comment by ericdallo** [comment]
I forgot to mention it worked here, sorry.

Glad to hear it :D

Thank you for the help!
